services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaForte!123
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      # A flag -C foi adicionada estrategicamente para confiar no certificado do SQL 2022
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SuaSenhaForte!123", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_crud_app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=CrudDb;User Id=sa;Password=SuaSenhaForte!123;TrustServerCertificate=True
    depends_on:
      db:
        condition: service_healthy
    command: sleep infinity

volumes:
  sql_data:
